# Generated by Django 5.2.3 on 2025-07-29 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('cost', models.IntegerField(blank=True, null=True)),
                ('unit', models.CharField(blank=True, max_length=15, null=True)),
                ('quantity', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
