# Generated by Django 5.2.3 on 2025-07-29 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tjtAdmin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenses',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
