# Generated by Django 5.2.3 on 2025-08-12 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tjtAdmin', '0002_expenses_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=20)),
                ('time', models.CharField(max_length=100)),
                ('page', models.CharField(max_length=20)),
            ],
        ),
    ]
