# Generated by Django 5.2.3 on 2025-08-13 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tjtAdmin', '0003_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='action',
            field=models.CharField(default='', max_length=20),
        ),
    ]
