# Generated by Django 5.2.3 on 2025-08-17 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tjtAdmin', '0004_notifications_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='page',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
