# Generated by Django 5.2.3 on 2025-06-26 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0002_shippingaddress_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='street',
            new_name='address',
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
