# Generated by Django 5.2.3 on 2025-06-26 18:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0004_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='discount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='invoice.discount'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='percentage',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=5),
        ),
    ]
