# Generated by Django 5.2.3 on 2025-06-28 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0005_order_discount_alter_discount_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_method',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
