# Generated by Django 5.2.3 on 2025-06-28 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0007_delivery_alter_order_delivery_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='delivery_fee',
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_fee',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
