# Generated by Django 5.2.3 on 2025-07-03 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0008_remove_delivery_delivery_fee_order_delivery_fee'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ShippingAddress',
            new_name='DeliveryAddress',
        ),
    ]
