# Generated by Django 5.2.3 on 2025-07-04 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0009_rename_shippingaddress_deliveryaddress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryaddress',
            name='mobile_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
